seed = 0
parent_dir = "exp/CT/tab_ddpm2"
real_data_path = "data/CT/"
model_type = "mlp"
num_numerical_features = 148
device = "cuda:0"

[model_params]
is_y_cond = true
d_in = 109
num_classes = 5

[model_params.rtdl_params]
d_layers = [
    256,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 30000
lr = 0.00027761965839603165
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 5400
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
